name: Push Docker image
description: Download, load, and push Docker image tags

inputs:
  registry:
    description: Container registry hostname
    required: true
  image:
    description: Fully qualified image name
    required: true
  version:
    description: Image version
    required: true
  registry-token:
    description: Container registry authentication token
    required: true

runs:
  using: composite
  steps:
    - name: Download Docker image
      uses: actions/download-artifact@v8
      with:
        name: docker-image

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.registry-token }}

    - name: Load and push image tags
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        VERSION: ${{ inputs.version }}
      run: |
        docker load --input image.tar
        IMAGE_TAG="$VERSION-${GITHUB_SHA::7}"
        docker push "$IMAGE:latest"
        docker push "$IMAGE:$IMAGE_TAG"